---
- name: include 12.04 if required
  include: 12.04.yml
  when: ansible_distribution_version == "12.04"

- name: Install zabbix and dependencies
  apt: name={{ item }} state=latest update_cache=yes
  with_items:
      - zabbix-agent
      - python-pip
      - atop
      - bc
      - smartmontools

- name: Install ZTC
  pip: name=ztc
  
- name: Remove ztc configs
  file: dest=/etc/zabbix-agent.d
        state=absent
        
- name: Create configs dir
  file: dest=/etc/zabbix/zabbix_agentd.d
          owner=zabbix
          group=zabbix
          mode=500
          state=directory

- name: Copy configs to client
  copy: src=zabbix_agentd.d dest=/etc/zabbix
          owner=zabbix
          group=zabbix
          mode=400
          directory_mode=500
  notify:
    - restart zabbix-agent
  
- name: Create scripts dir
  file: dest=/etc/zabbix/scripts
          owner=zabbix
          group=zabbix
          mode=500
          state=directory

- name: Copy scripts to client
  copy: src=scripts dest=/etc/zabbix
        owner=zabbix
        group=zabbix
        mode=500
        directory_mode=500

- name: zabbix sudoers
  copy: src=sudoers.d/zabbix-nopasswd dest=/etc/sudoers.d/zabbix-nopasswd
        owner=root
        group=root
        mode=0440

- name: Generate zabbix config file
  template: src=zabbix_agentd.conf.jinja dest=/etc/zabbix/zabbix_agentd.conf
            owner=root
            group=root
            mode=0644
  notify:
    - restart zabbix-agent       
      
- name: Delete default user-parameter conf
  file: dest=/etc/zabbix/zabbix_agentd.d/userparameter_mysql.conf.dpkg-dist
        state=absent

- name: atop logrotate fix for 14.04
  copy: src=logrotate.d/atop dest=/etc/logrotate.d/atop
          owner=root
          group=root
          mode=644
  when: ansible_distribution_version == "14.04"
