- name: install the official repo
  yum: name=http://repo.zabbix.com/zabbix/3.0/rhel/7/x86_64/zabbix-release-3.0-1.el7.noarch.rpm

- name: Install zabbix and dependencies
  yum: name={{ item }} state=latest
  with_items:
      - zabbix-agent
      - python-pip
      - atop
      - bc
      - smartmontools
